name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: |
          echo "Hello World! "
          echo "Welcome to my revision class"
      - name: print goodbye
        run: echo "Done. Goodbye"
    
  
